; ---------------------------------------------------------------------------
; DURANGO HARDWARE CONSTANTS
; @author: Emilio Lopez Berenguer emilio@emiliollbb.net
; @author: Carlos Santisteban Salinas zuiko21@gmail.com
; @author: Victor Suárez García zerasul@gmail.com
; ---------------------------------------------------------------------------

; [HiRes Invert S1 S0    RGB LED NC NC]
VIDEO_MODE = $DF80
INT_ENABLE = $DFA0
GAMEPAD1 = $DF9C
GAMEPAD2 = $DF9D
VSP = $DF93
VSP_CONFIG = $DF94
SYNC = $DF88
SCREEN_0 = $0000
SCREEN_1 = $2000
SCREEN_2 = $4000
SCREEN_3 = $6000
MATRIX_KEYBOARD = $DF9B
