;
; File generated by cc65 v 2.17 - Debian 2.17-1
;
	.fopt		compiler,"cc65 v 2.17 - Debian 2.17-1"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_waitFrames
	.import		_fillScreen
	.export		_main

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	jmp     L0004
L0002:	ldx     #$00
	lda     #$11
	jsr     _fillScreen
	ldx     #$00
	lda     #$32
	jsr     _waitFrames
	ldx     #$00
	lda     #$77
	jsr     _fillScreen
	ldx     #$00
	lda     #$1E
	jsr     _waitFrames
	ldx     #$00
	lda     #$22
	jsr     _fillScreen
	ldx     #$00
	lda     #$32
	jsr     _waitFrames
L0004:	jmp     L0002
	ldx     #$00
	lda     #$00
	jmp     L0001
L0001:	rts

.endproc

